name: CI Workflow

on:
  push:
    branches:
      - main
      - week-10-automation
      - '**'
  pull_request:
    branches:
      - main
      - week-10-automation
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: echo "Run your tests here!"
